---
ID: "a32713f8-fd74-49bf-9833-d7ed5064a33b"
Parent: "cebfa804-440e-4891-a8cc-8dc51057667a"
Template: "814c1dbb-b118-4511-ba2b-7288ed3d490b"
Path: /sitecore/system/Modules/Layout Service/Rendering Contents Resolvers/Products/Product List
SharedFields:
- ID: "52b17c6d-d151-46c5-a986-b88050073ef0"
  Hint: UseContextItem
  Value: 1
- ID: "de218ede-a9ad-4b04-86c5-9ff593ccf39d"
  Hint: Type
  Value: BasicCompany.Feature.Products.LayoutService.ProductListContentsResolver, BasicCompany.Feature.Products
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200729T192919Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "abc87f62-c93b-4e89-b3a6-1f4ecacb16ba"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200729T193257Z
